name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i
      - run: npm i -g vsce
      - run: vsce publish -p $MS_PAT
        env:
          MS_PAT: ${{secrets.MS_PAT}}
